/* Generated By:JavaCC: Do not edit this line. AnalisadorVisitor.java Version 5.0 */
public interface AnalisadorVisitor
{
  public Object visit(SimpleNode node, Object data);
}
/* JavaCC - OriginalChecksum=8e2da065f5efc9329f2f93c3e63d0501 (do not edit this line) */
